# File path to the tennis environment
tennis_env: "./Tennis_Linux/Tennis.x86_64"
# Maximum number of training episodes
n_episodes: 3000
# Maximum number of timesteps per episode
max_timesteps: 1000
# Size of the replay buffer
buffer_size: 100000
# Minibatch size for training
batch_size: 1024
# Update (learn) the model parameters after every n steps
update_every: 7
# Number of times to update the networks 
network_update: 10
# Discount rate
gamma: 0.99
# Soft update of target network parameters
tau: 1.0E-3
# Learning rate of the actor
lr_actor: 1.0E-4
# Learnig rate of the critic
lr_critic: 1.0E-3
# L2 weight decay
weight_decay: 0.0
# Preferred device (GPU or CPU)
device: GPU
# Random seed
random_seed: 42
# Ornstein-Uhlenbeck mu
ou_mu: 0.0
# Ornstein-Uhlenbeck theta
ou_theta: 0.15
# Ornstein-Uhlenbeck sigma
ou_sigma: 0.19
# Initial noise factor
noise_start: 1.0
# Factor to reduce noise in each episode
noise_reduce: 0.9995
# Minimal noise factor (lower bound)
noise_min: 0.1
# Desired average reward
total_avg_reward: 0.6
# Number of episodes for average reward
scores_window: 100
